### ISSUE TITLE
Bug: Dependency cycle: CommandProcessor <-> BidiServer <-> EventManager

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#1079]
The relevant files to break the cycle in are:

- CommandProcessor.ts
- BidiServer.ts
- EventManager.ts
- networkProcessor.ts

Originally appeared on https://github.com/GoogleChromeLabs/chromium-bidi/pull/1064.

This cycle is problematic whenever one `async` / `await` method appears somewhere downstream in the CommandProcessor.

**Comment by thiagowfx** [comment]
We ended up working around this for Network Interception but it may still be a good idea to fix it at some point.

**Comment by Lightning00Blade** [comment]
Closing this, as I think we don't have the issue any more.
