### ISSUE TITLE
Network and Fetch domain activation

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#1080]
Currently, the network domain is incorrectly enabled.

The network domain should be enabled via the CDP client/target, only when the browsing context has...

- ...subscriptions to `network.` events, and/or
- ..._global_ subscription to the network namespace

It's important to not do `Network.enable` globally, otherwise we'd emit too many unnecessary CDP events, when the client may not be interested in them.

Edit(2023-09-11): @Lightning00Blade: It seems that if we never enable interception we always call `Fetch.disable` on target create, I think it would be good it we omit that that way its a little bit faster for WPT and other test.

cc @Lightning00Blade

**Comment by sadym-chromium** [comment]
> cc @sadym-chromium FYI as this slightly relates to supporting multiple BiDi/CDP sessions.

ack

**Comment by thiagowfx** [comment]
`Fetch` is partially resolved via #1409.

**Comment by Lightning00Blade** [comment]
This should be resolved and we should be enabling both `Network` and `Fetch` only when needed.
