### ISSUE TITLE
Docs: Move internal g3doc into external README.md

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#1091]
We should extract the good parts of http://go/bidi-g3doc to the `README.md` file in this repository or, alternatively, to a `docs/` directory.

**Comment by thiagowfx** [comment]
@sadym-chromium suggested to document the https://www.conventionalcommits.org/en/v1.0.0/#summary workflow in the README.md.

cc @jrandolf 

In general, when we introduce new patterns, we should try to document them.

**Comment by OrKoN** [comment]
Probably we do not want to proceed with this
