### ISSUE TITLE
Python / `pip`: Code scanning alerts and environment management

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#1182]
https://github.com/GoogleChromeLabs/chromium-bidi/security/code-scanning has some suggestions to add hashes to `requirements.txt` (`pip`) for python, similarly to how we do for github action checkouts.

In order to effectively manage this, we should consider adopting some python environment manager. A few popular choices include `pipenv`, `poetry`, `tox`. At a quick glance, `poetry` seems to be a sensible choice.

Note: `pyenv` is just a version manager, and `pipx` is just a runner.

Originally reported by @Lightning00Blade via Chat.

**Comment by thiagowfx** [comment]
This is blocked on https://github.com/jwodder/anys/pull/3.

**Comment by thiagowfx** [comment]
Trying out with `pipenv` here: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1480.

**Comment by thiagowfx** [comment]
A list of resources:

- https://github.com/actions/setup-python/blob/65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236/docs/advanced-usage.md#caching-packages
- https://github.com/speced/bikeshed/blob/main/Pipfile
- https://docs.pytest.org/en/latest/reference/customize.html#configuration-file-formats

**Comment by thiagowfx** [comment]
This is technically closed but I'll keep it open for two reasons:

- [ ] find a way to install / bootstrap `pipenv` deterministically (with pinning / hash)
- [ ] evaluate the other frameworks (especially `poetry` and `tox`)

**Comment by OrKoN** [comment]
Closing for now
