### ISSUE TITLE
Clarify delta between WPT test scores on our dashboard vs. wpt.fyi (aka: GitHub Pages not being updated on failure)

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#1196]
- [x] Add a date to GH page to know the last update.
- [x] Versions
  - [x] Chrome
  - [x] Mapper (commit hash?)
  - [x] WPT (commit hash?)
- [x] Allow some reporting of the runs that fail (Logs already have the report)
- [x] Custom runs of WPT should not update site (or at least not main page)

**Comment by mathiasbynens** [comment]
It might be worth reporting the versions of Chrome and the Mapper itself (commit hash?) being tested on the report page.

**Comment by thiagowfx** [comment]
Added to the task list in the first comment, thanks for the suggestion!
