### ISSUE TITLE
Get WPT tests passing

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/chromium-bidi#121]

**Comment by whimboo** [comment]
Hi @mathiasbynens. Is there actually a way to see which of the wpt tests are currently passing and which not? Given that results aren't published on [wpt.fyi](https://wpt.fyi/results/webdriver/tests/bidi?label=master&label=experimental&product=chrome&product=firefox&product=safari) it's hard to discover. Thanks!

**Comment by foolip** [comment]
I'm afraid not, no. One could look at https://github.com/GoogleChromeLabs/chromium-bidi/tree/main/wpt-metadata/webdriver/tests/bidi to answer the question for a specific test, but there's no way to visualize it, and we're not uploading results to wpt.fyi yet. That wouldn't be super hard to do, but right now there are quite few passing tests so maybe after that's improved a bit.

**Comment by sadym-chromium** [comment]
Closing in favor of specific WPT tests subset

**Comment by mathiasbynens** [comment]
> Closing in favor of specific WPT tests subset

https://github.com/GoogleChromeLabs/chromium-bidi/issues?q=is%3Aissue+is%3Aopen+label%3Awpt
