### ISSUE TITLE
WPT test warning after all runs

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#1266]
In local and CI runs we get the following error:

```
0:00.05 WARNING Falling back to getting metadata update properties from wptrunner browser product file, this will be removedTraceback (most recent call last):  File "/usr/local/google/home/nvitkov/bidi/wpt/wpt", line 10, in <module>    wpt.main()  File "/usr/local/google/home/nvitkov/bidi/wpt/tools/wpt/wpt.py", line 233, in main    rv = script(*args, **kwargs)         ^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/google/home/nvitkov/bidi/wpt/tools/wpt/update.py", line 44, in update_expectations    update_properties = metadata.get_properties(properties_file=kwargs["properties_file"],                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/google/home/nvitkov/bidi/wpt/tools/wptrunner/wptrunner/metadata.py", line 107, in get_properties    properties, dependents = products.load_product_update(config, product)                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/google/home/nvitkov/bidi/wpt/tools/wptrunner/wptrunner/products.py", line 54, in load_product_update    module = product_module(config, product)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/google/home/nvitkov/bidi/wpt/tools/wptrunner/wptrunner/products.py", line 9, in product_module    raise ValueError("Unknown product %s" % product)
```

Most likely there was a WPT infra change related to metadata, that could explain why our auto-update expectations have not been working lately.

**Comment by thiagowfx** [comment]
Possibly related: https://github.com/web-platform-tests/wpt/issues/41184

**Comment by thiagowfx** [comment]
Yup, this is the same as the issue above.

"product" is deprecated: https://github.com/web-platform-tests/wpt/blame/49d6aa17ff973bd570aec96f322b145b47977360/tools/wptrunner/wptrunner/metadata.py#L4

So we should remove `--product chrome` from our script.

That said, when we do it, we hit the same error as gsnedders@ in the bug above.

**Comment by thiagowfx** [comment]
Possible culprit: https://github.com/web-platform-tests/wpt/commit/64082e7b0d5f34648dd227b14de68966ba1943aa

**Comment by thiagowfx** [comment]
@foolip: Do you know how this issue could be resolved?

**Comment by foolip** [comment]
@thiagowfx I'm not familiar with the changes that caused this breakage, so I don't know off hand. But feel free to ping me if you try to debug this and can't work out how to fix it.

**Comment by Lightning00Blade** [comment]
Closing as not an issue on our end, and I can't repo any more.
