### ISSUE TITLE
Mapper debugging for events is emitting wrong information: methods instead of events

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#1309]
Observed: Event names are represented as "method"s.

Expected: Event names are represented as "event"s.

<img width="744" alt="image" src="https://github.com/GoogleChromeLabs/chromium-bidi/assets/2840106/57d0ab69-f08e-4814-ae18-f207ebce0946">

e.g. https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent

cc @sadym-chromium @Lightning00Blade

**Comment by thiagowfx** [comment]
It's not quite obvious to me in which file we should change `method` to `event`.

**Comment by OrKoN** [comment]
This comes from CDP and I don't think we should change it https://source.chromium.org/chromium/chromium/src/+/main:third_party/inspector_protocol/crdtp/dispatch.cc;l=368;drc=31fb07c05718d671d96c227855bfe97af9e3fb20

**Comment by thiagowfx** [comment]
Ah, gotcha, I thought it was from the mapper.

If it's from CDP, given the high cost to change it, it's better to leave it alone.
