### ISSUE TITLE
Mouse input events are failing validation tests in WPT

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#1328]
See https://github.com/web-platform-tests/wpt/pull/42081/checks?check_run_id=16968626580

Many test cases that verify errors on invalid input are accepted by Chromium.

**Comment by OrKoN** [comment]
@jrandolf PTAL

**Comment by jrandolf** [comment]
That's currently known. Chromium/Chromium BiDi doesn't have full support for all properties right now.

**Comment by jrandolf** [comment]
Blocked on https://github.com/w3c/webdriver/pull/1800
