### ISSUE TITLE
`navigation` value should always be present, even for wait=none

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#1332]
`BrowsingContext.navigate` and `BrowsingContext.reload` should have `navigation` value even in case of `wait: none`.

In BiDi, the [`await a navigation](https://w3c.github.io/webdriver-bidi/#await-a-navigation) step generates a new `navigation` UUID for each navigation disregard of the wait condition. Even in case of same document [fragment navigation](https://html.spec.whatwg.org/multipage/browsing-the-web.html#navigate-fragid).

In CDP:
* [Page.navigate](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate)'s `loaderId ` is omitted in case of same-document navigation, as the previously committed loaderId would not change.
* [Page.reload](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-reload) does not provide any `loaderId`. The `loaderId` can be retrieved only from the `Page.lifecycleEvent` of from the network events.

Currently, the `navigation` is not provided in case of reloading with wait `none` or same-document navigation. 

WPT tests: https://wpt.fyi/results/webdriver/tests/bidi/browsing_context/navigate/hash.py?label=master&label=experimental&aligned

**Comment by thiagowfx** [comment]
Upstream: https://github.com/w3c/webdriver-bidi/issues/532
