### ISSUE TITLE
Using `omitBackground` in `captureScreenshot`

### ISSUE THREAD

**Issue by jrandolf** [GoogleChromeLabs/chromium-bidi#1344]
Opened this issue to discuss whether we should by default omit backgrounds on `captureScreenshot`. Firefox already has this behavior of screenshots and IMO if the format is `png`, we should be omitting the background as that's probably what's expected from the user.

**Comment by OrKoN** [comment]
does the spec say anything about that?

**Comment by jrandolf** [comment]
The spec doesn't say anything about this.

**Comment by Lightning00Blade** [comment]
Closing this we should either use `goog:` values or open an issue on spec.
