### ISSUE TITLE
`test_input_performActions* ` e2e test is flaky

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#1407]
e2e tests of input are flaky. Example:

`test_input_performActionsEmitsDragging`:
https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/6448243919/job/17509797173?pr=1403

Although the output is really hard to read, the difference is expected and missing the following part at the beginning: 
```
      {
        type: 'object',
        value: [
          [
            'event',
            {
              type: 'string',
              value: 'mousemove',
            },
          ],
          [
            'button',
            {
              type: 'number',
              value: 0,
            },
          ],
          [
            'buttons',
            {
              type: 'number',
              value: 0,
            },
          ],
          [
            'clientX',
            {
              type: 'number',
              value: 630,
            },
          ],
          [
            'clientY',
            {
              type: 'number',
              value: 336,
            },
          ],
        ],
      },
```

Another example:

`test_input_performActionsEmitsPointerEvents`:
Example: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/6548857552/job/17784481994?pr=1443
Related: https://github.com/GoogleChromeLabs/chromium-bidi/issues/1407

**Comment by jrandolf** [comment]
This is a result of headful mode. The solution is to disable the test in headful.

**Comment by sadym-chromium** [comment]
> This is a result of headful mode. The solution is to disable the test in headful.

Cannot we make the test more flexible, so that it tolerates the fluctuations?

**Comment by sadym-chromium** [comment]
friendly ping

**Comment by sadym-chromium** [comment]
another example: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/6509030633/job/17679618738

**Comment by sadym-chromium** [comment]
The issue addressed, expectations do not tolerate flakiness anymore
