### ISSUE TITLE
`test_fail_request_completes_new_request_still_blocks` e2e test is flaky

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#1428]
The test is flaky on headful. Example: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/6507248949/job/17674295005
This causes false-negative CI runs.

**Comment by thiagowfx** [comment]
Ack

**Comment by thiagowfx** [comment]
The request fails because it is fetching some image: ` 'url': 'data:image/png;ba `. Huh.
