### ISSUE TITLE
"Google Search" scenario works in Safari

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#156]

**Comment by thiagowfx** [comment]
@sadym-chromium Why do we care about a Safari bug in the mapper repo?

**Comment by sadym-chromium** [comment]
The same reason we have spec issues in this repo: to keep track of them, even if they are not directly related to the Mapper implementation.

**Comment by Lightning00Blade** [comment]
Out of scope for this repo.
