### ISSUE TITLE
Umbrella bug for Browser Permissions API

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#1585]
BiDi spec extension: https://github.com/w3c/permissions/pull/425
Permissions spec: https://www.w3.org/TR/permissions/#automation

cc @Lightning00Blade @OrKoN 

This bug is being filed to track the implementation commitment in the Chromium Mapper side.

**Comment by OrKoN** [comment]
No longer relevant.
