### ISSUE TITLE
Chrome passes WPT `browsingContext.navigate`

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#169]
- [x] #136 
  - [x] [Pure BiDi WPT tests for `browsingContext.navigate`](https://github.com/web-platform-tests/wpt/pull/34372)
  - [x] #189
  - [x] #183 
  - [x] #184
  - [x] #188
  - [x] #220
  - [x] [wpt-metadata/.../bidi/browsing_context/navigate](https://github.com/GoogleChromeLabs/chromium-bidi/tree/main/wpt-metadata/webdriver/tests/bidi/browsing_context/navigate) is removed.

**Comment by whimboo** [comment]
Note that we are currently working on more tests to cover a lot of different scenarios, whereby most of them already landed over the last couple of days.
