### ISSUE TITLE
eslint warnings for classes with only static methods

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#1727]
/Users/alexrudenko/src/chromium-bidi/src/bidiMapper/domains/script/SharedIdParser.ts
  20:14  warning  Unexpected class with only static properties  @typescript-eslint/no-extraneous-class

/Users/alexrudenko/src/chromium-bidi/src/bidiServer/WebSocketServer.ts
  57:14  warning  Unexpected class with only static properties  @typescript-eslint/no-extraneous-class

**Comment by Lightning00Blade** [comment]
By Google Typescript Style guide we should either refactor to use a new with proper properties or use functions - https://google.github.io/styleguide/tsguide.html#container-classes

**Comment by Lightning00Blade** [comment]
Closed by #1740 #1739
