### ISSUE TITLE
Out of Memory when BiDi is enabled

### ISSUE THREAD

**Issue by joerg1985** [GoogleChromeLabs/chromium-bidi#1839]
The DOM of the BiDi-CDP Mapper tab does grow unlimited, this results in a out of memory issue in this tab.
Depending on the available RAM it might take some time to run into this issue.

Minimal code to reproduce the issue using selenium is listed below.
When running real code this usually happens faster, as more things are logged. 

```
        var options = new org.openqa.selenium.chrome.ChromeOptions();
        options.setCapability("webSocketUrl", true);

        WebDriver driver = new org.openqa.selenium.chrome.ChromeDriver(options);

        for (int i = 0; i < 1_000_000_000; i++) {
            driver.navigate().refresh();
        }
```

**Comment by sadym-chromium** [comment]
Completed in https://github.com/GoogleChromeLabs/chromium-bidi/pull/1846. Please verify.
