### ISSUE TITLE
Race condition between events from Fetch and Network domains causes a deadlock

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#1883]
[Example](https://github.com/GoogleChromeLabs/chromium-bidi/files/14376561/rewuest_intercept_cdp.log) of the following events order:
1. Network.requestWillBeSentExtraInfo
1. Network.responseReceivedExtraInfo
1. Fetch.requestPaused
1. Network.requestWillBeSent

This causes the deadlock for whatever reason. Repro: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1880

**Comment by OrKoN** [comment]
Note Nik is currently actively working on this and the best repro is one captured in the unit test https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/bidiMapper/domains/network/NetworkStorage.spec.ts#L344
