### ISSUE TITLE
Emit "browsingContext.contextCreated" events for all open browsing contexts when subscribing to the event

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#1902]
The remote end subscribe steps in the spec require us to emit created events for every open browsing context.

https://w3c.github.io/webdriver-bidi/#ref-for-remote-end-subscribe-steps%E2%91%A1

**Comment by Lightning00Blade** [comment]
Duplicate of #1077, consider closing one.

**Comment by Lightning00Blade** [comment]
Closed by https://github.com/GoogleChromeLabs/chromium-bidi/pull/2255
