### ISSUE TITLE
WPT test `/webdriver/tests/bidi/input/perform_actions/invalid.py` slow in CI and local

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#1903]
The test file contains 400 test and runs in 60sec on my CloudTop and timeout on CI as well, on WPT infra it run in 23sec so the test pass. We should find a way to either speed it up, split it or increase the timeout only for it.

**Comment by whimboo** [comment]
Do you have logs which indicate why it is that slow on your CloudTop?

**Comment by OrKoN** [comment]
@whimboo it also times out for me locally for Firefox:

```
python3 ./wpt run --channel=nightly firefox webdriver/tests/bidi/input/perform_actions/invalid.py
```

Interestingly, setting the timeout multiplier to 1 makes it faster and finish in 7 sec:

```
python3 ./wpt run --channel=nightly firefox webdriver/tests/bidi/input/perform_actions/invalid.py --timeout-multiplier=1
```

**Comment by whimboo** [comment]
> Here are logs - https://gist.github.com/Lightning00Blade/715b201c0921841fd2d884b118fb8a43

Interesting there are around 100ms between each test. Formerly I found a bug with Chrome and `Set Window Rect` but that should be fixed via https://github.com/web-platform-tests/wpt/pull/43853. Maybe you could check with debug logs enabled?

> @whimboo it also times out for me locally for Firefox:
> 
> ```
> python3 ./wpt run --channel=nightly firefox webdriver/tests/bidi/input/perform_actions/invalid.py
> ```
> 
> Interestingly, setting the timeout multiplier to 1 makes it faster and finish in 7 sec:
> 
> ```
> python3 ./wpt run --channel=nightly firefox webdriver/tests/bidi/input/perform_actions/invalid.py --timeout-multiplier=1
> ```

I don't see timeouts when checking the [history on wpt.fyi](https://wpt.fyi/results/webdriver/tests/bidi/input/perform_actions/invalid.py?label=master&label=experimental&product=firefox&product=firefox_android&product=chrome&product=chrome_android&product=safari&aligned&view=subtest). 

Also running it locally it takes 12s whether which timeout multiplier is set - also note that it should not make a difference in runtime related to the value as set. Maybe run with `--webdriver-arg=-vv` to get trace logs which might indicate where that extra time is needed on your local machine.

**Comment by OrKoN** [comment]
So it looks like it is flaky, sometimes it ends within 7sec, sometimes times out after 30sec. Timing out log  https://gist.githubusercontent.com/OrKoN/79e9ba8995db27fbf51bfe71d6f9fc28/raw/e10ead37d89d7baee486d7f59e7fad8a2cbe5d46/gistfile1.txt

**Comment by whimboo** [comment]
This is interesting:

```
 0:08.48 pid:43164 1709045559009	webdriver::server	DEBUG	<- 200 OK {"value":["14d9c636-71b7-4acc-a1c5-2b31a627f25a"]}
 0:34.55 DEBUG Got command: 'log'
 0:34.55 INFO STDOUT: webdriver/tests/bidi/input/perform_actions/invalid.py::test_params_input_source_action_sequence_actions_actions_invalid_type[None-pointer] 
 0:34.55 DEBUG Got command: 'log'
 0:34.55 INFO STDOUT: ERROR
 0:34.55 DEBUG Got command: 'log'
 0:34.55 INFO STDOUT: webdriver/tests/bidi/input/perform_actions/invalid.py::test_params_input_source_action_sequence_actions_actions_invalid_type[None-wheel] 
```

Usually it should look like:

```
0:07.57 DEBUG Got command: 'log'
 0:07.57 INFO STDOUT: webdriver/tests/bidi/input/perform_actions/invalid.py::test_params_context_invalid_type[value3] 
 0:07.57 pid:43164 1709045558098	RemoteAgent	INFO	Perform WebSocket upgrade for incoming connection from 127.0.0.1:58608
```

It's not clear to me what's going on at this point. Would you mind filing a bug for that so that we can track the work in Bugzilla? Also please mention how often this happens, and if that doesn't happen when you modify the timeout multiplier. Thanks.

**Comment by OrKoN** [comment]
@whimboo I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1882533

**Comment by Lightning00Blade** [comment]
So If i comment out - https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/support/helpers.py#L54
The test run consistently in 12 sec, if I enable them they take around 45-60 sec.

**Comment by Lightning00Blade** [comment]
So the fall where it fails is here - https://github.com/web-platform-tests/wpt/commit/d2b7ac0b46e174bf40d555781cb9fa7970b9d716#diff-5bca3d8b5c6c48d3020bc6bfcc2d5b6b95882e8c9de3fb35c237293d18b25ed5R67 
 `is_maximized` return `true`. 
 CC @nechaev-chromium let's chat offline

**Comment by nechaev-chromium** [comment]
For the context:
The timeout mentioned earlier by Maxim is in [chrome_impl::SetWindowBounds].(https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/chrome/chrome_impl.cc;l=303;drc=644874afbd6aa7c5de82636ad52d6b298c34a458;bpv=1;bpt=1?q=SetWindowBounds&ss=chromium%2Fchromium%2Fsrc:chrome%2Ftest%2Fchromedriver%2F).
This is how the timeout appeared: [chromedriver:2663](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2663).
Another bug report [chromium:41403879](https://g-issues.chromium.org/issues/41403879) relates to the code below the timeout in question. The complaint was that due to window animations on MacOS the state did not change in time therefore causing flakiness.

**Comment by Lightning00Blade** [comment]
This is now fixed by https://chromium-review.googlesource.com/c/chromium/src/+/5366899
