### ISSUE TITLE
test_remove_intercept_unblocks is flaky

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#2027]
See https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/8344865962/job/22838354837?pr=2026

cc @Lightning00Blade

**Comment by Lightning00Blade** [comment]
@sadym-chromium There seems to be a regression with the latest changes in test runner. I can't see CDP logs for the E2E failures when I download the logs. Could you please investigate or tell me if you can't?

**Comment by sadym-chromium** [comment]
ack

**Comment by sadym-chromium** [comment]
> @sadym-chromium There seems to be a regression with the latest changes in test runner. I can't see CDP logs for the E2E failures when I download the logs. Could you please investigate or tell me if you can't?

https://github.com/GoogleChromeLabs/chromium-bidi/pull/2029

**Comment by Lightning00Blade** [comment]
I have not seen this E2E test flake now, closing.
