### ISSUE TITLE
ERROR tests/browser/test_create_user_context.py::test_browser_create_user_context[websocket0] is flaky time out

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#2041]
cc @Lightning00Blade @sadym-chromium any ideas? it didn't time out before and there are also no user context related events. Has anything changed w.r.t. to browsing contexts? I have seen this failure a couple of times today.

Example failure: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/8362146671/job/22892014453

**Comment by sadym-chromium** [comment]
looks like the flakiness is over. The test is re-enabled
