### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#2056]
As of 2024-01, the waiting time was ~15 minutes which makes it more difficult to land changes. We should reduce the runtime of CI jobs as much as possible.

* [ ] CI jobs time is under 5 minutes (6 minutes now)
* [ ] CI is not flaky

**Comment by Lightning00Blade** [comment]
I think we are good with the latest changes, if we want to go under 5 min we need to update the shards number.
For flakiness we should track individual test rather then one place.
