### ISSUE TITLE
CI should run `interop` test to prevent regressions on our end 

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#2133]
Currently we run only test that are in the `webdriver/tests/bidi` we should have a separate job for running the `webdriver/tests/interop` . We should also have a separate view on the Web site.

- [x] Run `webdriver/tests/interop` in CI as separate job.
- [x] Have a page that shows `webdriver/tests/interop` tests

**Comment by whimboo** [comment]
Just another idea... maybe you could run all the tests under `webdriver/tests` and exclude `classic`?

**Comment by Lightning00Blade** [comment]
Done by #2350
