### ISSUE TITLE
Update EsLint to V9.X.X and update other dependencies

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#2180]
We need to update the config used to be `flat` and update other things as necessary.
https://eslint.org/docs/latest/use/migrate-to-9.0.0

**Comment by xiomaraR** [comment]
I'd like to work on this!

**Comment by Lightning00Blade** [comment]
@xiomaraR I would be happy to review a PR.

**Comment by Lightning00Blade** [comment]
With https://github.com/GoogleChromeLabs/chromium-bidi/pull/2493 we moved to flat config, but some plugins are still not supported.
