### ISSUE TITLE
Quick WPT generates HTML reports

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#2240]
There are 2 github actions to run WPT:
* [Detailed WPT](https://github.com/GoogleChromeLabs/chromium-bidi/blob/09e2cfeaa0f26a81759ccf631d54841e5f806af6/.github/workflows/wpt.yml). It tuns all the bidi tests in a single run, which takes ~20 minutes, it uses [tools/wpt-report-builder/builder.mjs](https://github.com/GoogleChromeLabs/chromium-bidi/blob/09e2cfeaa0f26a81759ccf631d54841e5f806af6/tools/wpt-report-builder/builder.mjs) script to generate 2 html reports, which are published [here](https://googlechromelabs.github.io/chromium-bidi) and [here ](https://googlechromelabs.github.io/chromium-bidi/2023). The only reason **Detailed WPT** is in place is the report generation.
* [Quick WPT](https://github.com/GoogleChromeLabs/chromium-bidi/blob/09e2cfeaa0f26a81759ccf631d54841e5f806af6/.github/workflows/wpt-quick.yml). It shards tests, and takes ~6 minutes. However, it cannot generate html report.

In order to speed up html report generation, and to avoid multiple actions doing more or less same tasks, we want to get rid of **Detailed WPT**. This reqiures:
* [x] Make [tools/wpt-report-builder/builder.mjs](https://github.com/GoogleChromeLabs/chromium-bidi/blob/09e2cfeaa0f26a81759ccf631d54841e5f806af6/tools/wpt-report-builder/builder.mjs) support not a single report, but a list or WPT reports to generate HTML report for. https://github.com/GoogleChromeLabs/chromium-bidi/pull/2441
* [x] In **Quick WPT**, if required, generate and publish HTML report based on the reports from the sharded runs.
* [x] Remove **Detailed WPT**.

**Comment by Lightning00Blade** [comment]
Closed as complete.
