### ISSUE TITLE
Implement network.setCacheBehavior 

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#2385]
See https://w3c.github.io/webdriver-bidi/#command-network-setCacheBehavior (roughly maps to https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCacheDisabled)

Types roll: https://github.com/GoogleChromeLabs/chromium-bidi/pull/2384

**Comment by OrKoN** [comment]
@sadym-chromium PTAL if you have a chance

**Comment by sadym-chromium** [comment]
types roll: https://github.com/GoogleChromeLabs/chromium-bidi/pull/2386
