### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#240]
WPT tests for logging should pass: https://wpt.fyi/results/webdriver/tests/bidi/log?label=master&label=experimental&aligned&q=webdriver&view=subtest

**Comment by whimboo** [comment]
@sadym-chromium please note that I'm currently removing all the `current_session.execute_script` calls in the log.entryAdded tests over in https://bugzilla.mozilla.org/show_bug.cgi?id=1784532. Most likely these are blocking you here.

**Comment by sadym-chromium** [comment]
@whimboo thanks for the heads-up! We'll wait for migration then.

**Comment by whimboo** [comment]
The sync is going to happen via https://github.com/web-platform-tests/wpt/pull/35513

**Comment by whimboo** [comment]
The sync is done and all traces for `current_session` are gone from the bidi tests. Do these tests work for you now?

**Comment by sadym-chromium** [comment]
We don't have message caching implemented, so the tests still don't pass on our side. WIP.

**Comment by sadym-chromium** [comment]
@whimboo another problem is in the fact WPT tests having specific value of the `text` field, while spec says: 
> If arg is a [primitive ECMAScript value](https://tc39.es/ecma262/#sec-primitive-value), append [ToString](https://tc39.es/ecma262/#sec-tostring)(arg) to text. Otherwise append an implementation-defined string to text.

**Comment by whimboo** [comment]
This should actually be related to the discussion on https://github.com/w3c/webdriver-bidi/issues/139. The webdriver tests should most likely check for `any_string` in the `text` field?

**Comment by juliandescottes** [comment]
@sadym-chromium do you want to update the tests yourself as part of your work, or should we do it?

**Comment by sadym-chromium** [comment]
I'll publish PR with that + removing verification of implementation-defined `text` field.

**Comment by sadym-chromium** [comment]
https://github.com/web-platform-tests/wpt/pull/35577

**Comment by sadym-chromium** [comment]
Implemented.
