### ISSUE TITLE
Two child contexts if navigated twice

### ISSUE THREAD

**Issue by vladimir-nechaev** [GoogleChromeLabs/chromium-bidi#248]
If a document that has a child frame is navigated twice the resulting document has two child browsing contexts.
This bug is responsible for [chromedriver:4204](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4204) leading to several failing WPT tests.
The patch to chromium-bidi with the reproducer can be found attached to [chromedriver:4204](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4204): [View](https://bugs.chromium.org/p/chromedriver/issues/attachmentText?aid=567673), [Download](https://bugs.chromium.org/p/chromedriver/issues/attachment?aid=567673&signed_aid=Pc-5iPAZU0mYuTsS1HuTww==)

**Comment by sadym-chromium** [comment]
Fixed in #254
