### ISSUE TITLE
Feature: Mention examining the log file as a next step on E2E test failure

### ISSUE THREAD

**Issue by alexnj** [GoogleChromeLabs/chromium-bidi#2549]
Currently the E2E CLI does not offer much as a next step during a failure scenario. The log file name is stated upfront on initialization, but it's a hard to miss detail if one doesn't know what they are looking for. 

I think we could improve this for the novice user by adding an additional line post failure recognition, something like: `Additional information might be available in <logfile>`.

**Comment by OrKoN** [comment]
cc @Lightning00Blade
