### ISSUE TITLE
Chrome passing WPT tests for "console.log" scenario

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#260]
- [x] Folder [`wpt-metadata/webdriver/tests/bidi/log`](https://github.com/GoogleChromeLabs/chromium-bidi/tree/main/wpt-metadata/webdriver/tests/bidi/log) is removed.
- [x] [WPT.fyi tests](https://wpt.fyi/results/webdriver/tests/bidi/log?label=experimental&label=master&aligned&view=subtest) are passing.

**Comment by sadym-chromium** [comment]
UPD: Added the second point to fix the wpt.fyi.

**Comment by sadym-chromium** [comment]
As of 2022-11-23 the [WPT log tests](https://wpt.fyi/results/webdriver/tests/bidi/log?label=experimental&label=master&aligned&view=subtest) have `0 / 45` passes. Hypothesis is it is due to the [WPT downloads the old version of ChromeDriver](https://github.com/web-platform-tests/wpt/blob/181bb8b142309c7491f1a485851000481b14be15/tools/wpt/browser.py#L922), which should be fixed after ChromeDriver Beta release after 2022-12-01.

**Comment by whimboo** [comment]
@sadym-chromium is there a nightly version of chromedriver available for download? Might be an option to have the Nightly tests on wpt run with that version instead. We do that for geckodriver.

**Comment by sadym-chromium** [comment]
Not officially, but the following trick can be done:
* Get [the latest version](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?generation=1669217493384422&alt=media).
* Get binary from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/{the latest version}/

**Comment by whimboo** [comment]
James actually told me that for Chrome the dev channel is used. As such the idea that I had in my last comment is not doable, and we will have to wait.

**Comment by whimboo** [comment]
So it means that it's actually not that bad and changes in Chrome/chromedriver could be tested earlier? Maybe even for the dev channel?

**Comment by sadym-chromium** [comment]
> So it means that it's actually not that bad and changes in Chrome/chromedriver could be tested earlier? Maybe even for the dev channel?

The next dev release should contain the patch. We are prioritizing the early WPT ChromeDriver runs.

**Comment by sadym-chromium** [comment]
UPD: the dev release on 2022-12-15 should contain [the patch](https://crrev.com/c/4084871).

**Comment by sadym-chromium** [comment]
The WPT still uses ChromeDriver wihtout the fix: [`Starting ChromeDriver 110.0.5464.0`](https://community-tc.services.mozilla.com/tasks/PxTGc3HCRgCy7RYYB_74AQ/runs/0/logs/public/logs/live.log#L635). Investigating.

**Comment by sadym-chromium** [comment]
Attempt to fix the ChromeDriver revision issue: https://github.com/web-platform-tests/wpt/pull/37577

**Comment by sadym-chromium** [comment]
The [`wpt-versions/pinned_chromium_revision`](https://storage.googleapis.com/wpt-versions/pinned_chromium_revision) is updated. Waiting for the next WPT run.

**Comment by whimboo** [comment]
Looks like this works now:

https://wpt.fyi/results/webdriver/tests/bidi/log/entry_added?label=master&product=firefox%5Bexperimental%5D&product=chrome%5Bexperimental%5D&product=edge%5Bexperimental%5D&product=safari&aligned&view=subtest

**Comment by sadym-chromium** [comment]
Yes, except 3 tests. Should be fixed by this: https://github.com/web-platform-tests/wpt/pull/37675.

**Comment by sadym-chromium** [comment]
Done.
