### ISSUE TITLE
`net::ERR_BLOCKED_BY_CLIENT` errors is Chromium and Canary

### ISSUE THREAD

**Issue by christian-bromann** [GoogleChromeLabs/chromium-bidi#2761]
I started to see issues in Chromium and now in Canary:

> WebDriver Bidi command "browsingContext.navigate" failed with error: unknown error - net::ERR_BLOCKED_BY_CLIENT

Chrome version used: `v132.0.6824.0`

The Bidi command used:

```
browsingContext.navigate {"context":"0AEB79806DB013EF2C4E6A601F2DA7E3","url":"http://guinea-pig.webdriver.io/","wait":"complete"}
```

Any information if this is a bug in Chrome or something related to how WebdriverIO uses the protocol?

**Comment by OrKoN** [comment]
I could not reproduce with Puppeteer. But I think usually BLOCKED_BY_CLIENT is related to some ad blockers etc.

**Comment by christian-bromann** [comment]
I was able to reproduce it with the following code:

```js
import { remote } from 'webdriverio'

const browser = await remote({
    capabilities: {
        browserName: 'chrome',
        browserVersion: 'stable'
    }
})

await browser.url('http://guinea-pig.webdriver.io')
await browser.pause(2000)
await browser.deleteSession()
```

It seems the problem here is that the page is `http` which results in a failure of opening the page:
<img width="1150" alt="Screenshot 2024-11-07 at 12 22 28 PM" src="https://github.com/user-attachments/assets/92370a43-ba78-4ba1-86eb-41a295d5c598">

This seems to start happening in Chrome with Canary.

**Comment by OrKoN** [comment]
Got, filed https://crbug.com/378022921. Can be disabled by disabling HttpsFirstBalancedModeAutoEnable. Let's follow on the upstream issue.
