### ISSUE TITLE
Do not emit navigation events for the initial navigation

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#2793]
As discussed in [`browsingContext.navigationStarted` for the initial navigation to `about:blank`](https://github.com/w3c/webdriver-bidi/issues/766), no navigation events ("browsingContext.domContentLoaded",        "browsingContext.load", "browsingContext.navigationStarted") should be emitted on the initial navigation to `about:blank`.

**Comment by OrKoN** [comment]
> should be emitted on the initial navigation to about:blank.

to clarify: there seems to be no initial navigation to about:blank according to the html spec. We we need to issue a historyUpdated event when applicable.

**Comment by sadym-chromium** [comment]
I consider the initial issue is addressed. Closing.
