### ISSUE TITLE
[Umbrella] Prototype, spec and implement `script.addPreloadScript`

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#283]
## Tracking

- [x] #295
- [x] #294
- [x] #293
- [x] #297 
- [ ] #296

**Comment by thiagowfx** [comment]
Given that we already have a Milestone (https://github.com/GoogleChromeLabs/chromium-bidi/milestone/15), this Umbrella is effectively a duplicate. Closing, in favour of the Milestone.
