### ISSUE TITLE
Implement `channel` mechanism

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#294]
https://github.com/w3c/webdriver-bidi/issues/157

Prototype the mechanism using long-poll. Implementation details: http://go/webdriver-binding-implementation.

## Status

- [x] Prefactoring: https://github.com/GoogleChromeLabs/chromium-bidi/pull/542
- [x] Introduce `Script.Message`: https://github.com/GoogleChromeLabs/chromium-bidi/pull/541
- [x] Implement binding mechanism: https://github.com/GoogleChromeLabs/chromium-bidi/pull/319

**Comment by thiagowfx** [comment]
Spec work seems to be in progress in https://github.com/w3c/webdriver-bidi/pull/361/files

**Comment by thiagowfx** [comment]
@sadym-chromium can this be closed?
