### ISSUE TITLE
[Upstream] Specification for `channel` mechanism

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#295]
Propose the result of #294 as a specification. 
Spec issue: https://github.com/w3c/webdriver-bidi/issues/157

The spec should be accompanied by the WPT tests. 
Design doc: http://go/webdriver-binding-implementation.

**Comment by thiagowfx** [comment]
@sadym-chromium Can we close this?

**Comment by thiagowfx** [comment]
This was implemented upstream: https://github.com/w3c/webdriver-bidi/pull/361
