### ISSUE TITLE
Implement `channel` mechanism in preload script

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#296]
Doc: https://docs.google.com/document/d/1rI078gHjmR1cL1cjKtrGoDAsJoDVLkX_aF64pc8hgOs/edit#heading=h.7nki9mck5t64

`script.addLoadScript` should be able to communicate back to client. 

Add the binding mechanism similar to #294, #295. 

Probably, only binding names can be provided, and the created script will have bindings with provided names as an argument:
```
{
  method: "script.addLoadScript", 
  params: {
    function: "(binding1, binding2)=>{binding1('some_event')'}"
    bindings: ["BINDING_NAME_1", "BINDING_NAME_2"]
  }}
```

Research is needed, as CDP bindings don't support WebDriver serialisation.

## Tracking

- [x] add `arguments` to `add preload script`
- [x] implement `channel` mechanism in preload script
- [x] make WPT tests pass

**Comment by thiagowfx** [comment]
Could you help me start this one, as https://github.com/GoogleChromeLabs/chromium-bidi/pull/319 is very close to get merged?

**Comment by sadym-chromium** [comment]
Implementation details are described in http://go/chrome-devtools:bootstrap-bindings-proposal

**Comment by sadym-chromium** [comment]
Done in #857
