### ISSUE TITLE
Add example script for `console.log` scenario

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#315]
Add an example script running the foloowing scenario using WebDriver BiDi. It should work with ChromiumBiDi, ChromeDriver, EdgeDriver, Firefox.
1. Open a page.
2. Subscribe to log events.
3. Evaluate `console.log` on the page.
4. Wait for [`log.entryAdded`](https://w3c.github.io/webdriver-bidi/#event-log-entryAdded) event.

**Comment by thiagowfx** [comment]
- KR: Chromium-BiDi supports “console.log” scenario
- Priority: P1
- Note: Scenario is focused on the main advantage BiDi vs Classic: async events. Tracking: https://github.com/GoogleChromeLabs/chromium-bidi/milestone/13
- Note: Missing parts: log caching.

**Comment by sadym-chromium** [comment]
> * Note: Missing parts: log caching.

It is implemented in https://github.com/GoogleChromeLabs/chromium-bidi/issues/258

**Comment by thiagowfx** [comment]
Looking into this. Should we create `tests/test_console_log.py` or should we augment `tests/test_log_events.py`?

**Comment by sadym-chromium** [comment]
It should be a script like [`examples/cross-browser.py`](https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/examples/cross-browser.py) in [`examples`](https://github.com/GoogleChromeLabs/chromium-bidi/tree/main/examples) folder. Probably, `examples/cross-browser.py` should be renamed to something like `script_example.py`.
