### ISSUE TITLE
ChromeDriver Classic + BiDi WPT runner

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#348]
To keep track of ChromeDriver mapper, consider running daily WPT tests on the latest ChromeDriver version with a separate expectations folder.

Context:
Currently we [run](https://github.com/GoogleChromeLabs/chromium-bidi/actions/workflows/wpt.yml) the [WPT tests](https://github.com/web-platform-tests/wpt) with BiDi-only Mapper for [each PR](https://github.com/GoogleChromeLabs/chromium-bidi/blob/16be3142fe0cf75fe3d0e9a8d62aa652f6ed2b5e/.github/workflows/wpt.yml#L8) and each[ merge in `main`](https://github.com/GoogleChromeLabs/chromium-bidi/blob/16be3142fe0cf75fe3d0e9a8d62aa652f6ed2b5e/.github/workflows/wpt.yml#L10).

We run WPT with ChromeDriver Classic + BiDi only as a part of [wpt.fyi](https://wpt.fyi/results/webdriver/tests/bidi?label=master&label=experimental&aligned&view=subtest) on dev, which is released bi-weekly. 

Examples of regressions in ChromeDriver vs Mapper:
1. [`browsingContext.create`: `referenceContext `](https://wpt.fyi/results/webdriver/tests/bidi/browsing_context/create/reference_context.py?run_id=5067278387773440&run_id=6215205571264512&run_id=6308490167975936&run_id=6263447839309824&view=subtest).
2. [`console.log`](https://wpt.fyi/results/webdriver/tests/bidi/log?run_id=5067278387773440&run_id=6215205571264512&run_id=6308490167975936&run_id=6263447839309824).
3. [`script.getRealms`](https://wpt.fyi/results/webdriver/tests/bidi/script/get_realms/get_realms.py?run_id=5067278387773440&run_id=6215205571264512&run_id=6308490167975936&run_id=6263447839309824).

Consider running [WPT tests](https://github.com/web-platform-tests/wpt) with canary ChromeDriver more often to be notified about potential regressions faster. This can be either a daily task in this repo, or in any other place. TBD

Alternatively, if [ChromeDriver allowed custom Mapper binaries](https://crbug.com/chromedriver/4216), the CI can be run with the current Mapper version, to shorten the feedback loop.

**Comment by thiagowfx** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4216 is resolved

And now we have both `wpt-mapper` and `wpt-chromedriver` actions.

Is this issue resolved?

**Comment by thiagowfx** [comment]
> the CI can be run with the current Mapper version, to shorten the feedback loop.

...is https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/wpt-chromedriver.yml thanks to `          --webdriver-arg="--bidi-mapper-path=lib/iife/mapperTab.js"`

**Comment by sadym-chromium** [comment]
Implemented in [`.github/workflows/wpt-chromedriver.yml`](https://github.com/GoogleChromeLabs/chromium-bidi/blob/9ecfbb7b640f613c8d269e5434b2a563fa6e0c43/.github/workflows/wpt-chromedriver.yml).
