### ISSUE TITLE
Reduce the number of static methods and variables

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#392]
Install https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-extraneous-class.md to detect completely static classes.

How to fix static:

1) if it's a readonly static property used as a const move it to the top module level `const MY_CONST = ..`. Export it if other modules need it.
2) if it's a property holding runtime data, the data should not be stored globally but be scoped to a bidi mapper session.
3) after the data is made local, the static methods should either become a module-level functions or non-static methods operating on the local data.

**Comment by OrKoN** [comment]
The following are static data properties:

ScriptEvaluator.#knownHandlesToRealm
Realm.#realmMap

These should be scoped to src/bidiMapper/BidiServer.

**Comment by thiagowfx** [comment]
![dependencygraph](https://user-images.githubusercontent.com/2840106/215522014-6c854882-165b-430f-b3bc-25e02e5d392d.svg)

Refer to https://github.com/GoogleChromeLabs/chromium-bidi/pull/422#issuecomment-1408841439 to see how this graph was generated.

**Comment by thiagowfx** [comment]
@OrKoN regarding ScriptEvaluator.#knownHandlesToRealm and  Realm.#realmMap: should both of these also become instances of `BidiServer`?

Also: For `realm` you had mentioned earlier to create a `RealmStorage` wrapper. How about `ScriptEvaluator`?

**Comment by OrKoN** [comment]
@thiagowfx yeah, I think the knownHandlesToRealm can be part of the realm storage as it is related to realms too.
