### ISSUE TITLE
BidiMapper should not trigger unhandled promise rejections

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#411]
Rejections like https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/bidiMapper/domains/context/browsingContextImpl.ts#L422 are not handled by the mapper. This results in the process shutdown in Node.

cc @thiagowfx @sadym-chromium

**Comment by thiagowfx** [comment]
What is the AI here? I.e. how should they be handled?

**Comment by OrKoN** [comment]
Promises should be caught and handled without unhandled rejection.

**Comment by sadym-chromium** [comment]
I assume Ale meant this line [permalink to `browsingContextImpl.ts`](https://github.com/GoogleChromeLabs/chromium-bidi/blob/2cdbd8ab932d27091a810fe26fc017fa296502a3/src/bidiMapper/domains/context/browsingContextImpl.ts#L449)

**Comment by sadym-chromium** [comment]
> Could you confirm if this is somewhat the desired intent?
> 
> From:
> 
> ```
> this.#targetDefers.documentInitialized.reject('Document changed');
> ```
> 
> To:
> 
> ```
> this.#targetDefers.documentInitialized.catch((error: unknown) => {
>   debug('Document changed', error);
> });
> ```

Yes, that's fine. By the time it was written, it was unclear how this case should be resolved. But now we have a good argument not to throw an exception.

**Comment by thiagowfx** [comment]
Sounds good, will take this over now.
