### ISSUE TITLE
BiDiMapper should only show logs when needed

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#421]
Logs coming from https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/utils/log.ts#L26 are always show.  It should only show them under some condition - Example would be debugging or the https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/bidiTab/bidiTab.ts that uses it to display logs. 

Suggestions:
Something similar to the Puppeteer [Debug](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/Debug.ts) can be implemented or the ability to provide a custom logger to `chromium-bidi` can be added.

**Comment by thiagowfx** [comment]
- [ ] First comment
- [ ] Thanks. I also need to check if the logic on https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/utils/log.ts#L26 still works, especially given https://github.com/GoogleChromeLabs/chromium-bidi/pull/420/files.

**Comment by OrKoN** [comment]
@thiagowfx let's make sure that the debug library is not statically imported in the bidiMapper subfolder
