### ISSUE TITLE
[WPT_ChromeDriver] Unstable test `test_multiple_top_level_contexts[window\]`

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#437]
The test `test_multiple_top_level_contexts[window\]` is unstable in the ChromeDriver. Should be investigated.

* [Successful run](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/4161727434/jobs/7200044138).
* [Failed run](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/4161727442/jobs/7200044073).

**Comment by thiagowfx** [comment]
<img width="1161" alt="image" src="https://github.com/GoogleChromeLabs/chromium-bidi/assets/2840106/ddab787f-6066-463f-8d98-eccd713183a8">
