### ISSUE TITLE
Missing HTML escaping in WPT HTML report

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/chromium-bidi#454]
https://github.com/GoogleChromeLabs/chromium-bidi/blob/f9978cb56d8b5df5f5a9766d7f7dbf7bb6e3351a/test-report/htmlWptReport.mjs#L111

`subtest.name` needs HTML-escaping, (e.g. via [`_.escape`](https://lodash.com/docs/4.17.15#escape)).

Some of the test names include e.g. “`<lambda>`” and these are currently not getting rendered correctly.

**Comment by mathiasbynens** [comment]
I guess this bug should be closed since #458 landed.

> Possibly related: <img alt="image" width="1267" src="https://user-images.githubusercontent.com/2840106/237207134-7688cd80-a577-43b7-9f9b-d9e2b738ece5.png">

What's the issue here?

**Comment by thiagowfx** [comment]
Ah, then let's close it and file a new one. I'll answer your question in the new issue I'll crete.

**Comment by thiagowfx** [comment]
https://github.com/GoogleChromeLabs/chromium-bidi/issues/699
