### ISSUE TITLE
[WPT_ChromeDriver] Unstable test `test_invalid_address[port\]`

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#463]
* `test_invalid_address[port\]`
  * [Successful run](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/4223622892/jobs/7333572888).
  * [Failed run](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/4223670993/jobs/7333678497#step:10:3643).
* test_invalid_address[host\]
  * [Successful run](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/4223622892/jobs/7333572888).
  * [Failed run](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/4242115910/jobs/7373201773#step:10:766).

**Comment by thiagowfx** [comment]
When I run it locally, it passes ~all the time.

Maybe the instability is present solely in the CI environment.
