### ISSUE TITLE
Add `HTMLCollection` to CDP serialization

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#471]
Umbrella chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1420968

Add `HTMLCollection` type to CDP serialization `generateWebDriverValue` to fulfil the BiDi specification ["value is a **platform object** that implements **HTMLCollection**"](https://w3c.github.io/webdriver-bidi/#data-types-protocolValue-RemoteValue-serialization).

**Comment by thiagowfx** [comment]
Closing in favor of tracking it in https://github.com/GoogleChromeLabs/chromium-bidi/issues/562
