### ISSUE TITLE
Align `Node` serialization with specification

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#472]
Umbrella chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1420968

Updated [node serialization WPT](https://github.com/w3c/webdriver-bidi/pull/335) failed the following tests:
    1. `wpt-metadata/webdriver/tests/bidi/script/call_function/result_node.py.ini`;
    2. `wpt-metadata/webdriver/tests/bidi/script/evaluate/result_node.py.ini`.

**Comment by thiagowfx** [comment]
Closing in favor of tracking it in https://github.com/GoogleChromeLabs/chromium-bidi/issues/562
