### ISSUE TITLE
`session.unsubscribe` should be atomic

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#482]
The command `session.unsubscribe` should be atomic. If operation failed to some reason (not subscribed, browsing context not found, etc):

Expected: nothing should be unsubscribed.
Actual: some of the events processed before the error happened are unsubscribed.

[Related WPT test](https://github.com/web-platform-tests/wpt/blob/ef22a833e19a288616e478ebaffe6f346bc53826/webdriver/tests/bidi/session/unsubscribe/invalid.py#L75).

**Comment by thiagowfx** [comment]
Code pointers:

https://github.com/GoogleChromeLabs/chromium-bidi/blob/471636bd9214be316087b918a98cff63baa6555d/src/bidiMapper/domains/events/EventManager.ts#L203

https://github.com/GoogleChromeLabs/chromium-bidi/blob/471636bd9214be316087b918a98cff63baa6555d/src/bidiMapper/domains/events/SubscriptionManager.ts#L165
