### ISSUE TITLE
Align general platform object serialization with specification

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#498]
Umbrella chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1420968

Add general platform object into CDP serialization `generateWebDriverValue` to fulfil the BiDi specification ["value is a **platform object**"](https://w3c.github.io/webdriver-bidi/#data-types-protocolValue-RemoteValue-serialization).

The difference with the general object is in not having field "value".

This should fix WPT tests `test_remote_values[new URL('https://example.com')` in 
* [`webdriver/tests/bidi/script/call_function/result.py`](https://wpt.fyi/results/webdriver/tests/bidi/script/call_function/result.py?label=master&label=experimental&aligned&view=subtest);
* [`webdriver/tests/bidi/script/evaluate/result.py`](https://wpt.fyi/results/webdriver/tests/bidi/script/evaluate/result.py?label=master&label=experimental&aligned&view=subtest).

**Comment by sadym-chromium** [comment]
This basically means that [`ThreadDebuggerCommonImpl::serializeToWebDriverValue`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/thread_debugger_common_impl.cc;drc=04159b02a986bdd73d461370aeb40dc7dbb576b3;l=301) has to check the `value` vs each of the [custom blink object](https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/third_party/blink/renderer/bindings/core/v8/).

There probably some ways to cut this corner.

**Comment by sadym-chromium** [comment]
After [Serialize dom wrappers (4303236) · Gerrit Code Review](https://crrev.com/c/4303236) is merged, Mapper can simply replace type `platformobject` with `object`. At least until specification is changed ([Should we serialize platform objects as JS objects with enumerable own properties included · Issue #352 · w3c/webdriver-bidi](https://github.com/w3c/webdriver-bidi/issues/352)).

**Comment by thiagowfx** [comment]
Related: https://github.com/GoogleChromeLabs/chromium-bidi/issues/562

**Comment by Lightning00Blade** [comment]
The test are passing and the discussion seem have concluded that we don't what to expose a special type at this point.
