### ISSUE TITLE
Bug: Navigation does not return correct url when page redirects.

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#513]
In Puppeteer we test that the navigation `browsingContext.navigate` follows redirects - [Test](https://github.com/puppeteer/puppeteer/blob/puppeteer-v19.7.3/test/src/navigation.spec.ts#L50)
When running headful mode I can see that the command navigates to the correct page, 
it's just not getting reported by Mapper correctly.

**Comment by thiagowfx** [comment]
From @sadym-chromium: The main blocker from our side at the moment is lack of infra to run different servers.

**Comment by OrKoN** [comment]
You can consider using https://github.com/puppeteer/puppeteer/tree/main/packages/testserver if you need a recent npm version we can restore publishing to npm.
