### ISSUE TITLE
Implement `browsingContext.print` (print to PDF)

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#518]
Implement [Add browsingContext.print command by jgraham · Pull Request #363 · w3c/webdriver-bidi](https://github.com/w3c/webdriver-bidi/pull/363/files).

CDP method: [`Page.printToPDF`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF).
Spec: https://w3c.github.io/webdriver-bidi/#command-browsingContext-print

## Tracking

- [x] Basic implementation
- [x] ~CDP does not have a `shrinkToFit` equivalent (c.f. [comment](https://github.com/GoogleChromeLabs/chromium-bidi/issues/518#issuecomment-1465967305))~ it is called `preferCSSPageSize`
- [x] Implement `shrinkToFit`
- [x] #577 
- [x] [Issue 1430696: CDP `Page.printToPDF` crashes on tiny pages](https://bugs.chromium.org/p/chromium/issues/detail?id=1430696)
- [x] [CDP `Page.printToPDF` throws invalid parameters exception on pages with tiny dimensions (e.g. 1x1 pixel) (cont.)](https://bugs.chromium.org/p/chromium/issues/detail?id=1454035)
- [x] (optional) Add E2E test: print to pdf -> open it in the browser (either `application/pdf` or `file:///`) -> take screenshot -> compare golden: https://chat.google.com/room/AAAAw7biRSY/UdLyoDHCNgM. Or similar: https://github.com/GoogleChromeLabs/chromium-bidi/pull/912 and #914
- [ ] Fix WPT tests [`/webdriver/tests/bidi/browsing_context/print/`](https://github.com/GoogleChromeLabs/chromium-bidi/tree/main/wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print)

**Comment by thiagowfx** [comment]
@sadym-chromium `shrinkToFit` does not have a CDP equivalent. What do we do in these situations? File a FR against CDP?

**Comment by sadym-chromium** [comment]
> What do we do in these situations?

In general there are 3 options:
1. Implement in CDP.
1. Implement on top of existing CDP functionality + some extra logic.
1. Roll back the spec part.

**Comment by thiagowfx** [comment]
> 1. Implement in CDP.

How can we do so? This was also suggested by @whimboo on https://github.com/web-platform-tests/wpt/pull/38931#issuecomment-1468350079

Could you give me a pointer to the CDP repo?

**Comment by sadym-chromium** [comment]
> > 1. Implement in CDP.
> 
> How can we do so? This was also suggested by @whimboo on [web-platform-tests/wpt#38931 (comment)](https://github.com/web-platform-tests/wpt/pull/38931#issuecomment-1468350079)
> 
> Could you give me a pointer to the CDP repo?

sent PM

**Comment by sadym-chromium** [comment]
@thiagowfx FYI there are bunch of new failing  tests in WPT: https://github.com/GoogleChromeLabs/chromium-bidi/pull/625/files

**Comment by thiagowfx** [comment]
```
  bidiMapper:mapperDebug:CDP  sent ▸ {
  "id": 11,
  "method": "Page.navigate",
  "params": {
    "url": "data:application/pdf;base64,JVBERi0xLjQKJdPr6eEKMSAwIG9iago8PC9DcmVhdG9yIChDaHJvbWl1bSkKL1Byb2R1Y2VyIChTa2lhL1BERiBtMTE2KQovQ3JlYXRpb25EYXRlIChEOjIwMjMwNjEyMjEwNjM4KzAwJzAwJykKL01vZERhdGUgKEQ6MjAyMzA2MTIyMTA2MzgrMDAnMDAnKT4+CmVuZG9iagozIDAgb2JqCjw8L0xlbmd0aCAwPj4gc3RyZWFtCgplbmRzdHJlYW0KZW5kb2JqCjIgMCBvYmoKPDwvVHlwZSAvUGFnZQovUmVzb3VyY2VzIDw8L1Byb2NTZXQgWy9QREYgL1RleHQgL0ltYWdlQiAvSW1hZ2VDIC9JbWFnZUldPj4KL01lZGlhQm94IFswIDAgMjI2NzcuMTE5IDE3MDA4LjA4XQovQ29udGVudHMgMyAwIFIKL1N0cnVjdFBhcmVudHMgMAovUGFyZW50IDQgMCBSPj4KZW5kb2JqCjQgMCBvYmoKPDwvVHlwZSAvUGFnZXMKL0NvdW50IDEKL0tpZHMgWzIgMCBSXT4+CmVuZG9iago1IDAgb2JqCjw8L1R5cGUgL0NhdGFsb2cKL1BhZ2VzIDQgMCBSPj4KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxNSAwMDAwMCBuIAowMDAwMDAwMjAyIDAwMDAwIG4gCjAwMDAwMDAxNTUgMDAwMDAgbiAKMDAwMDAwMDM3NiAwMDAwMCBuIAowMDAwMDAwNDMxIDAwMDAwIG4gCnRyYWlsZXIKPDwvU2l6ZSA2Ci9Sb290IDUgMCBSCi9JbmZvIDEgMCBSPj4Kc3RhcnR4cmVmCjQ3OAolJUVPRgo=",
    "frameId": "A45327FAB30B9B82E7B22502D73B7520"
  },
  "sessionId": "9371436D303A35CD0D25C2B137D48C64"
} +0ms
  bidiMapper:mapperDebug:CDP  received ◂ {
  "id": 11,
  "result": {
    "frameId": "A45327FAB30B9B82E7B22502D73B7520",
    "loaderId": "4C7ADCE66AA34C1EE27626ABB37C38EA",
    "errorText": "net::ERR_ABORTED"
  },
  "sessionId": "9371436D303A35CD0D25C2B137D48C64"
} +0ms
FAILED                                   [100%]
```

**Comment by devAtQ** [comment]
When will this feature be released?

**Comment by sadym-chromium** [comment]
Closing, as implemented without several WPT tests, which is not planned to fix.
