### ISSUE TITLE
Get write access on https://github.com/w3c/webdriver-bidi upstream spec repository

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#530]
Both @thiagowfx and @sadym-chromium should have `write` (doesn't need to be `admin`) access on https://github.com/w3c/webdriver-bidi, in order to make it easier to send PR contributions directly to it, keeping branches directly there, instead of forking to our personal github accounts.

Precedent: We both already have `write` access to https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/bidi (WPT). Having access to the spec repo is a natural extension to that.

## Status

- [x] @thiagowfx
- [x] @sadym-chromium

**Comment by thiagowfx** [comment]
Maybe @mathiasbynens or @foolip could help us with that. I am not sure if Maksim already has access, but I am pretty sure I still do not.

**Comment by sadym-chromium** [comment]
I already have write access to spec, but not to bidi

**Comment by thiagowfx** [comment]
@sadym-chromium Philip should have given us access to BiDi a few months ago (January 9th). Check your inbox for `[GitHub] @foolip has invited you to join the @web-platform-tests organization`

**Comment by thiagowfx** [comment]
Assigned to @foolip because he is present in https://github.com/orgs/w3c/people?query=foo

**Comment by thiagowfx** [comment]
Thanks Philip, done
