### ISSUE TITLE
`npm run format` hangs

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#545]
`npm run format` fails for me (Mac). The last output is from eslint, I guess and then it never resolves/times out/no errors printed:

```
wpt-metadata/README.md 2ms
```

**Comment by OrKoN** [comment]
@thiagowfx

**Comment by thiagowfx** [comment]
Already fixed via https://github.com/GoogleChromeLabs/chromium-bidi/commit/ce16c831952f1a18ce2e04ddea8b1c7d0ff52b80

```
-    "format": "npm run eslint && npm run prettier & npm run yapf",
+    "format": "npm run eslint && npm run prettier && npm run yapf",
```
