### ISSUE TITLE
Screenshot E2E tests fail on different platforms (CI vs local macOS vs local Linux)

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#547]
Edit by @thiagowfx:

https://github.com/GoogleChromeLabs/chromium-bidi/pull/558 mitigated the issue by making the test pass on both Github CI, local macOS and local Linux, but in general (as per @sadym-chromium) we should make the test platform (OS) agnostic.

## Original issue by @OrKoN:

```
npm run e2e-headless -- tests/test_screenshot.py -vv
```

<img width="2995" alt="Screenshot 2023-03-15 at 11 06 24" src="https://user-images.githubusercontent.com/399150/225276690-a3a0dac9-7435-4a85-b704-66530924a8ea.png">

## Tracking

- [x] Ping(2023-05-31): Fix screenshot difference: https://github.com/GoogleChromeLabs/chromium-bidi/pull/795

**Comment by OrKoN** [comment]
cc @thiagowfx

**Comment by sadym-chromium** [comment]
WPT tests are failing as well because of the screen dimensions

**Comment by OrKoN** [comment]
@sadym-chromium this is e2e on a local mac (not related to WPT failure)

**Comment by thiagowfx** [comment]
This is quite odd, because my platform is also macOS. I thought setting the viewport would be enough to make the test deterministic, but maybe there's something else we're missing.

**Comment by OrKoN** [comment]
@thiagowfx I think the display might matter

**Comment by sadym-chromium** [comment]
I assume it is somehow related to the "nightshift" setting of the mac.

**Comment by thiagowfx** [comment]
Tentatively sent  https://github.com/GoogleChromeLabs/chromium-bidi/pull/558 but I expect it will fail CI.

Possible workaround: Have the E2E test detect whether it's a CI environment. If it is, use one golden. If it's a local environment, use another.

**Comment by thiagowfx** [comment]
Fixed by #558

**Comment by thiagowfx** [comment]
Updated issue title and first comment to reflect current state.

**Comment by thiagowfx** [comment]
It's also different on Linux.

![Uploading image.png…]()
