### ISSUE TITLE
Extend `MaxDepth` serialization option

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#559]
Currently, only `maxDepth` of 0 or 1 supported. We need to support any depth serialization in order to re-create WebDriver Classic serialiation.

**Comment by thiagowfx** [comment]
Also: https://github.com/GoogleChromeLabs/chromium-bidi/blob/d2ed7983dc447f8729f3b60f05174b27e722431a/src/protocol-parser/protocol-parser.ts#L313

**Comment by thiagowfx** [comment]
@sadym-chromium is this feature done?

**Comment by sadym-chromium** [comment]
yes
