### ISSUE TITLE
Add local server

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#575]
To test some scenarios (OOPIF, redirects) and in the same time to keep the tests local, we need to have a possibility to run local server supporting different DNS aliases and SSL connections.

Requirements:
- [x] Custom response, including custom HTTP response codes
~~- [ ] (optional) DNS aliases~~ (can be done via Chrome CLI args)
- [x] SSL connections

WPT can be used as a reference.

## Tracking

- [x] Add local server support
- [x] Add a test for closing browsingContext after navigating to a faulty certificate page
- [x] Test for 200 page
- [x] Test for 301 page
- [x] Test for 401 page
- [x] Test for hanging response

**Comment by sadym-chromium** [comment]
Example where is can be needed: #513

**Comment by thiagowfx** [comment]
Some ideas:

- `http.server` from python: https://pythonbasics.org/webserver/ (via @OrKoN)
- `http-server` from npm: https://www.npmjs.com/package/http-server (via @mathiasbynens)

**Comment by OrKoN** [comment]
DNS aliases is a feature of Chrome and we don't need it in the server.

**Comment by thiagowfx** [comment]
I just stumbled upon https://pytest-httpserver.readthedocs.io/en/latest... @Maksim Sadym , I wonder if we could reuse most of that library for our purposes, instead of https://github.com/GoogleChromeLabs/chromium-bidi/pull/1359
> pytest-httpserver is a python package which allows you to start a real HTTP server for your tests. The server can be configured programmatically to how to respond to requests.> This project aims to provide an easy to use API to start the server, configure the request handlers and then shut it down gracefully. All of these without touching a configuration file or dealing with daemons.

It also supports TLS.

**Comment by thiagowfx** [comment]
>  SSL connections

This one can be marked as done (c.f. `bad_ssl_url`).

**Comment by mathiasbynens** [comment]
> > SSL connections
> 
> This one can be marked as done (c.f. `bad_ssl_url`).

Thanks!

**Comment by sadym-chromium** [comment]
Done
