### ISSUE TITLE
Race condition when processing messages in ProcessingQueue

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#605]
In some instances it's possible create a deadlock the processing queue. 
This happens in the following puppeteer test [`should fail when navigating to bad SSL`](https://github.com/puppeteer/puppeteer/blob/main/test/src/navigation.spec.ts#L161)
The navigation command is send with `id` the error is correctly handle and pushed to ProcessingQueue
but it never create an outbound response to the Transport.

Adding a hack to ProcessingQueue:46 to have
```
if (this.#isProcessing && this.#queue.length !== 1) {
``` 
unblocks the process but better solution should be created.

**Comment by sadym-chromium** [comment]
It's not a race condition. The issue is in the fact we don't process `Network.loadingFailed` event.
