### ISSUE TITLE
No `log.entryAdded` after navigation

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#620]
If we navigate to a page that log things on load (`ReadinessState == 'complete'`). 
An repo Puppeteer Script be seen at [#10032](https://github.com/puppeteer/puppeteer/issues/10032). 

After an investigation I was able to deduce that the `RealmStorage` is being cleared by the CDP `Page.frameNavigated` event.
And the `Runtime.executionContextCreated` event creates a new Realm.
The first event handler is Async while the second is Sync. I think we are creating a `new Realm` then the first is awaited and we delete all the old Realms for the BrowsingContext included the newly created on.

The line that is doing [this](https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/bidiMapper/domains/context/browsingContextImpl.ts#L282).

If I reorder the ` this.#realmStorage.deleteRealms` before `await this.#deleteChildren();` things work as expected.
Please check if there is a specific reason for the current order of operation.

**Comment by thiagowfx** [comment]
I wonder if we can replace

```
await this.#deleteChildren();

// Remove all the already created realms.
this.#realmStorage.deleteRealms({browsingContextId: this.contextId});
```

with

```
this.delete();
```

?

**Comment by thiagowfx** [comment]
I cannot reproduce it in BiDi. The following test passes:

```
@pytest.mark.asyncio
async def test_browsingContext_logAfterNavigation(websocket, context_id, html):
    await subscribe(websocket, "log.entryAdded")

    await send_JSON_command(
        websocket, {
            "method": "browsingContext.navigate",
            "params": {
                "url": html("<script>console.log('mylog');</script>"),
                "context": context_id,
                "wait": "complete"
            }
        })

    result = await wait_for_event(websocket, "log.entryAdded")
    assert result == {
        "method": "log.entryAdded",
        "params": AnyExtending({
            "text": "mylog",
        })
    }
```

**Comment by thiagowfx** [comment]
@sadym-chromium let me know if you manage to create a repro.

**Comment by Lightning00Blade** [comment]
I can confirm that the suggestion in [comment](https://github.com/GoogleChromeLabs/chromium-bidi/issues/620#issuecomment-1511610695) works, as long as it's not awaited.
