### ISSUE TITLE
Specify `Network` interception

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#643]
- [ ] https://github.com/w3c/webdriver-bidi/issues/66

**Comment by thiagowfx** [comment]
https://github.com/w3c/webdriver-bidi/issues/66

**Comment by thiagowfx** [comment]
Link to upstream PR: https://github.com/w3c/webdriver-bidi/pull/429

**Comment by thiagowfx** [comment]
Closing in favor of https://github.com/GoogleChromeLabs/chromium-bidi/issues/644
