### ISSUE TITLE
Specify and Implement `Network` interception

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#644]
- Upstream: https://github.com/w3c/webdriver-bidi/issues/66
- Roadmap: https://github.com/w3c/webdriver-bidi/blob/master/roadmap.md#replacing-resources-with-test-data

### Prototyping and scaffolding by Thiago
- [x] #2034

### Productionisation of Network Interception by Nikolay
- [ ] #2035

**Comment by Lightning00Blade** [comment]
Closing to be tracked in separate (specific) bug.
