### ISSUE TITLE
Implement `browsingContext.reload`

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#650]
Spec: https://w3c.github.io/webdriver-bidi/#command-browsingContext-reload

## Tracking

- [x] Implementation
  - [x] Handle `wait`: `interactive` and `complete` (implementation)
- [x] Ping(2023-05-31): E2E tests
  - [x] basic
  - [x] wait
  - [x] ~~`ignoreCache`: https://github.com/GoogleChromeLabs/chromium-bidi/pull/742~~
  - [x] Ping(2023-05-31): `ignoreCache`: https://github.com/GoogleChromeLabs/chromium-bidi/pull/794
- [x] WPT tests (upstream)
  - [x] validation: https://github.com/web-platform-tests/wpt/pull/39739
  - [x] functionality: https://github.com/web-platform-tests/wpt/pull/40134
- [x] ~~(?) support for local server~~

**Comment by OrKoN** [comment]
cc @sadym-chromium @thiagowfx (let me know if I overlooked it, perhaps types are not right)

**Comment by thiagowfx** [comment]
You didn't, it's indeed missing. I am sending an initial PR shortly.

**Comment by sadym-chromium** [comment]
It's odd that there are no WPT tests for the command

**Comment by whimboo** [comment]
Well, this command hasn't been implemented yet in Firefox. So you are very welcome to create the related wdspec tests. Thanks!

**Comment by thiagowfx** [comment]
Taking a stab at it here: https://github.com/web-platform-tests/wpt/pull/39739

**Comment by thiagowfx** [comment]
Upstream WPT CL is complete and approved. Just waiting for merge. Closing.
