### ISSUE TITLE
Prototype `browsingContext.findElement` command

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#67]
* https://webdriver.io/docs/api/webdriver/#findelement
* https://w3c.github.io/webdriver/#dfn-find-element

**Comment by sadym-chromium** [comment]
* https://github.com/puppeteer/puppeteer/blob/ac162c561ee43dd69eff38e1b354a41bb42c9eba/src/common/QueryHandler.ts#L218

**Comment by sadym-chromium** [comment]
#70

**Comment by thiagowfx** [comment]
Reverted by https://github.com/GoogleChromeLabs/chromium-bidi/pull/337
