### ISSUE TITLE
Use Chrome for Testing in CI instead of Chromium

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#693]
This was originally landed on https://github.com/GoogleChromeLabs/chromium-bidi/pull/683 but had to be reverted on https://github.com/GoogleChromeLabs/chromium-bidi/pull/683 due to flakiness.

## Tracking

- [x] #697
- [x] @OrKoN's suggestion: pin browser version instead of `latest`

**Comment by OrKoN** [comment]
This should be closed by https://github.com/GoogleChromeLabs/chromium-bidi/pull/703
