### ISSUE TITLE
once() method for CDP events

### ISSUE THREAD

**Issue by bwalderman** [GoogleChromeLabs/chromium-bidi#82]
There are a few instances of this pattern appearing in our code, used to listen for a single occurrence of an event:

```ts
const eventHandler = (params) => {
  cdpClient.Page.removeEventListener('frameStoppedLoading', eventHandler);
  // ... Do stuff ...
};

cdpClient.Page.addEventListener('frameStoppedLoading', eventHandler);
```

We could add a `.once()` method to encapsulate this pattern instead:

```ts
const params = await cdpClient.Page.once('frameStoppedLoading');
// ... Do stuff ...
```

**Comment by sadym-chromium** [comment]
Implemented via [`Deferred`](https://github.com/GoogleChromeLabs/chromium-bidi/blob/5eb3e2c860f5b77f9de64d637e3444a3144efeb9/src/utils/deferred.ts)
