### ISSUE TITLE
Implement `browser.close`

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#861]
https://w3c.github.io/webdriver-bidi/#command-browser-close

**Comment by thiagowfx** [comment]
Do we implement this at the mapper level or at the client (e.g. puppeteer) level?

**Comment by thiagowfx** [comment]
Would it just be a matter of calling https://vanilla.aslushnikov.com/?Browser.close at the mapper level?

**Comment by OrKoN** [comment]
it needs to be implemented on the mapper level I believe.  browser.close + making sure all required BiDi events are dispatched.

**Comment by Lightning00Blade** [comment]
Progressed tracked at #1117. I missed this issue.

**Comment by thiagowfx** [comment]
Closing as a duplicate.
