### ISSUE TITLE
Make tooling cross-platform (Linux, macOS, Windows)

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#876]
Currently, tools like runWPT.sh are not cross-platform as they use tools (e.g., nproc) that is not available everywhere by default. I suggest we re-write tools in JavaScript to make them work cross-platform.

### Platforms

- [x] Linux
- [x] macOS
- [ ] Windows: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1043

### Convert scripts from bash to node (`js`) or `ts`

- [x] `runBiDiServer.sh`: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1039
- [x] `runWPT.sh`: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1039
- [ ] `runWPTAll.sh`

**Comment by thiagowfx** [comment]
That's reasonable

**Comment by thiagowfx** [comment]
Updated the first comment to reflect tracking.
