### ISSUE TITLE
Optimize Mapper compiled code

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#89]
**Actual:** the rolled-up Mapper script `/src/.build/bidiMapper/mapper.js` has a size of **`748K`**, and the vast majority of the file is CDP string literals describing CDP methods, which are added for development convenience and are required for the functionality.

Removing those definitions reduces the size of the plain `/src/.build/bidiMapper/mapper.js` to **`68K`**, and minimizing afterwards leads to only **`28K`** source size.

**Expected:** the rolled-up Mapper script `/src/.build/bidiMapper/mapper.js` doesn't have unnecessary string literals and has a size of ~ **`30K`**.

**Comment by thiagowfx** [comment]
Maksim:

> Try to compile mapper, and check its size. The vast majority of the space is taken by the CDP method definitions.

**Comment by thiagowfx** [comment]
cc @vladimir-nechaev @mathiasbynens

The first commit that integrates terser has been already merged (c.f. #221). To close this bug I need more clarification from @sadym-chromium w.r.t.:

> Removing those definitions [CDP string literals describing CDP methods, which are added for development convenience and are required for the functionality]

Let me know how we can accomplish that.

**Comment by OrKoN** [comment]
I think it could be achieved by removing the following imports in the cdp client:

```
import * as browserProtocol from 'devtools-protocol/json/browser_protocol.json';
import * as jsProtocol from 'devtools-protocol/json/js_protocol.json';
```

Perhaps instead of generating classes at runtime based on JSON definitions, we could employ a Proxy?

**Comment by sadym-chromium** [comment]
> I think it could be achieved by removing the following imports in the cdp client:
> 
> ```
> import * as browserProtocol from 'devtools-protocol/json/browser_protocol.json';
> import * as jsProtocol from 'devtools-protocol/json/js_protocol.json';
> ```
> 
> Perhaps instead of generating classes at runtime based on JSON definitions, we could employ a Proxy?

@thiagowfx IDK how exactly to reach that, and the issue involves some research. Alex's approach looks promising.

**Comment by sadym-chromium** [comment]
Additionally I'd consider adding a step verifying the compiled size in the given diapason.

**Comment by thiagowfx** [comment]
> Additionally I'd consider adding a step verifying the compiled size in the given diapason.

That was a good idea! Done on https://github.com/GoogleChromeLabs/chromium-bidi/pull/224

**Comment by thiagowfx** [comment]
https://mariusschulz.com/blog/importing-json-modules-in-typescript:

> Now, we get a type error in line 2. TypeScript doesn't let us import a JSON module out of the box, just like that. This was a conscious design decision made by the TypeScript team: pulling in large JSON files could potentially [consume a lot of memory](https://github.com/Microsoft/TypeScript/pull/22167#issuecomment-385479553), which is why we need to opt into that feature by enabling the --resolveJsonModule compiler flag:

This is likely why the bidi mapper size is quite bloated.

**Comment by thiagowfx** [comment]
Basic preprocessing with `jq` to filter out types and events from the JSON file:

```
960K    node_modules/devtools-protocol/json/browser_protocol.json =>
284K    node_modules/devtools-protocol/json/browser_protocol_commands_only.json

168K    node_modules/devtools-protocol/json/js_protocol.json =>
60K     node_modules/devtools-protocol/json/js_protocol_commands_only.json

528K => 268K    src/.build/bidiMapper/mapper.js
```
